---
- name: Setup for the Ansible's Environment
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Add "/ect/ansible/hosts"
      blockinfile:
        path: /etc/ansible/hosts
        block: |
            [master]
            172.16.10.10
            [node1]
            172.16.10.11
            [node2]
            172.16.10.12
    - name: Configure Bashrc
      lineinfile:
        path: /home/vagrant/.bashrc
        line: "{{ item }}"
      with_items:
        - "alias ans='ansible'"
        - "alias anp='ansible-playbook'"
        - "alias ang='ansible-galaxy'"